// Station catalog from the KCI station endpoint (sta_id → name). Regenerate when
// KCI adds stations; names are title-cased for display.
export const STATION_CATALOG: Record<string, { name: string; area: 'jabodetabek' | 'yogyakarta' }> = {
  "AC": { name: "Ancol", area: "jabodetabek" },
  "AK": { name: "Angke", area: "jabodetabek" },
  "BJD": { name: "Bojonggede", area: "jabodetabek" },
  "BKS": { name: "Bekasi", area: "jabodetabek" },
  "BKST": { name: "Bekasi Timur", area: "jabodetabek" },
  "BOI": { name: "Bojong Indah", area: "jabodetabek" },
  "BOO": { name: "Bogor", area: "jabodetabek" },
  "BPR": { name: "Batu Ceper", area: "jabodetabek" },
  "BUA": { name: "Buaran", area: "jabodetabek" },
  "CBN": { name: "Cibinong", area: "jabodetabek" },
  "CC": { name: "Cicayur", area: "jabodetabek" },
  "CIT": { name: "Cibitung", area: "jabodetabek" },
  "CJT": { name: "Cilejit", area: "jabodetabek" },
  "CKI": { name: "Cikini", area: "jabodetabek" },
  "CKR": { name: "Cikarang", area: "jabodetabek" },
  "CKY": { name: "Cikoya", area: "jabodetabek" },
  "CLT": { name: "Cilebut", area: "jabodetabek" },
  "CSK": { name: "Cisauk", area: "jabodetabek" },
  "CTA": { name: "Citayam", area: "jabodetabek" },
  "CTR": { name: "Citeras", area: "jabodetabek" },
  "CUK": { name: "Cakung", area: "jabodetabek" },
  "CW": { name: "Cawang", area: "jabodetabek" },
  "DAR": { name: "Daru", area: "jabodetabek" },
  "DP": { name: "Depok", area: "jabodetabek" },
  "DPB": { name: "Depok Baru", area: "jabodetabek" },
  "DRN": { name: "Duren Kalibata", area: "jabodetabek" },
  "DU": { name: "Duri", area: "jabodetabek" },
  "GDD": { name: "Gondangdia", area: "jabodetabek" },
  "GGL": { name: "Grogol", area: "jabodetabek" },
  "GST": { name: "Gang Sentiong", area: "jabodetabek" },
  "JAKK": { name: "Jakarta Kota", area: "jabodetabek" },
  "JIS": { name: "Jakarta International Stadium", area: "jabodetabek" },
  "JTK": { name: "Jatake", area: "jabodetabek" },
  "JAY": { name: "Jayakarta", area: "jabodetabek" },
  "JMU": { name: "Jurang Mangu", area: "jabodetabek" },
  "JNG": { name: "Jatinegara", area: "jabodetabek" },
  "JUA": { name: "Juanda", area: "jabodetabek" },
  "KBY": { name: "Kebayoran", area: "jabodetabek" },
  "KDS": { name: "Kalideres", area: "jabodetabek" },
  "KLD": { name: "Klender", area: "jabodetabek" },
  "KLDB": { name: "Klender Baru", area: "jabodetabek" },
  "KMO": { name: "Kemayoran", area: "jabodetabek" },
  "KMT": { name: "Kramat", area: "jabodetabek" },
  "KPB": { name: "Kampung Bandan", area: "jabodetabek" },
  "KRI": { name: "Kranji", area: "jabodetabek" },
  "LNA": { name: "Lenteng Agung", area: "jabodetabek" },
  "MGB": { name: "Mangga Besar", area: "jabodetabek" },
  "MJ": { name: "Maja", area: "jabodetabek" },
  "MTR": { name: "Matraman", area: "jabodetabek" },
  "MRI": { name: "Manggarai", area: "jabodetabek" },
  "TLM": { name: "Metland Telagamurni", area: "jabodetabek" },
  "NMO": { name: "Nambo", area: "jabodetabek" },
  "PDRG": { name: "Pondok Rajeg", area: "jabodetabek" },
  "PDJ": { name: "Pondok Ranji", area: "jabodetabek" },
  "PI": { name: "Poris", area: "jabodetabek" },
  "PLM": { name: "Palmerah", area: "jabodetabek" },
  "POC": { name: "Pondok Cina", area: "jabodetabek" },
  "POK": { name: "Pondok Jati", area: "jabodetabek" },
  "PRP": { name: "Parung Panjang", area: "jabodetabek" },
  "PSE": { name: "Pasar Senen", area: "jabodetabek" },
  "PSG": { name: "Pesing", area: "jabodetabek" },
  "PSM": { name: "Pasar Minggu", area: "jabodetabek" },
  "PSMB": { name: "Pasar Minggu Baru", area: "jabodetabek" },
  "RJW": { name: "Rajawali", area: "jabodetabek" },
  "RU": { name: "Rawa Buntu", area: "jabodetabek" },
  "RW": { name: "Rawa Buaya", area: "jabodetabek" },
  "SDM": { name: "Sudimara", area: "jabodetabek" },
  "SRP": { name: "Serpong", area: "jabodetabek" },
  "SUDB": { name: "Sudirman Baru", area: "jabodetabek" },
  "SUD": { name: "Sudirman", area: "jabodetabek" },
  "SW": { name: "Sawah Besar", area: "jabodetabek" },
  "TB": { name: "Tambun", area: "jabodetabek" },
  "TEB": { name: "Tebet", area: "jabodetabek" },
  "TEJ": { name: "Tenjo", area: "jabodetabek" },
  "TGS": { name: "Tigaraksa", area: "jabodetabek" },
  "THB": { name: "Tanah Abang", area: "jabodetabek" },
  "TKO": { name: "Taman Kota", area: "jabodetabek" },
  "TNG": { name: "Tangerang", area: "jabodetabek" },
  "TNT": { name: "Tanjung Barat", area: "jabodetabek" },
  "TPK": { name: "Tanjung Priok", area: "jabodetabek" },
  "THI": { name: "Tanah Tinggi", area: "jabodetabek" },
  "UI": { name: "Universitas Indonesia", area: "jabodetabek" },
  "UP": { name: "Universitas Pancasila", area: "jabodetabek" },
  "BBN": { name: "Brambanan", area: "yogyakarta" },
  "CE": { name: "Ceper", area: "yogyakarta" },
  "DL": { name: "Delanggu", area: "yogyakarta" },
  "GW": { name: "Gawok", area: "yogyakarta" },
  "JN": { name: "Jenar", area: "yogyakarta" },
  "KT": { name: "Klaten", area: "yogyakarta" },
  "KTA": { name: "Kutoarjo", area: "yogyakarta" },
  "LPN": { name: "Lempuyangan", area: "yogyakarta" },
  "MGW": { name: "Maguwo", area: "yogyakarta" },
  "PWS": { name: "Purwosari", area: "yogyakarta" },
  "SLO": { name: "Solo Balapan", area: "yogyakarta" },
  "SWT": { name: "Srowot", area: "yogyakarta" },
  "WJ": { name: "Wojo", area: "yogyakarta" },
  "WT": { name: "Wates", area: "yogyakarta" },
  "YK": { name: "Yogyakarta", area: "yogyakarta" },
  "PL": { name: "Palur", area: "yogyakarta" },
  "SK": { name: "Solo Jebres", area: "yogyakarta" },
  "JBU": { name: "Jambu Baru", area: "jabodetabek" },
  "CT": { name: "Catang", area: "jabodetabek" },
  "CKL": { name: "Cikeusal", area: "jabodetabek" },
  "WLT": { name: "Walantaka", area: "jabodetabek" },
  "KRA": { name: "Karangantu", area: "jabodetabek" },
  "RK": { name: "Rangkasbitung", area: "jabodetabek" },
  "TOJB": { name: "Tonjong Baru", area: "jabodetabek" },
  "CLG": { name: "Cilegon", area: "jabodetabek" },
  "KEN": { name: "Krenceng", area: "jabodetabek" },
  "MER": { name: "Merak", area: "jabodetabek" },
}
